service: nekhilesh-api

provider: 
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 15
  stage: production
  region: us-east-2

function: 
api: 
  handler: lambda.handler
  events:
      - http: ANY {proxy+}
      - http: ANY /